version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "12345Aa!"
            ACCEPT_EULA: "Y"
        ports:
            - "5434:1433"